// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/__create/social-dev-shim": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/__create/social-dev-shim" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./__create/social-dev-shim/page.jsx": {
    id: "__create/social-dev-shim/page";
    page: "/__create/social-dev-shim";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "__create/social-dev-shim/page": typeof import("./src/app/./__create/social-dev-shim/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};